[tox]
envlist = py312,py313,py314

[testenv]
deps = pytest
       pytest-cov
       ujson
       py3-strongtyping312: strongtyping>=3.12,<3.13
       py3-strongtyping313: strongtyping>=3.13
       py3-strongtyping314: strongtyping>=3.13

commands = pytest tests --cov=strongtyping_pyoverload
